"""Regenerate CSS variables, token reference, contrast evidence and campaign SVGs.
Run with Python 3 from this directory. No dependencies or network required.
"""
from pathlib import Path
import json
import base64

ROOT = Path(__file__).resolve().parent
themes = {
    "light": {
        "canvas": "#F7F7F2", "surface": "#FFFFFF", "subtle": "#EEEFE7", "raised": "#FFFFFF",
        "text": "#181A18", "secondary": "#51564B", "muted": "#666D5E",
        "line": "#D8DBD1", "control": "#858C7A",
        "accent": "#DCDE8D", "accent-hover": "#D0D477", "on-accent": "#181A18",
        "accent-ink": "#59611F", "selected": "#EFF0D9", "focus": "#657023",
        "primary": "#181A18", "primary-hover": "#30362A", "on-primary": "#F7F7F2",
        "success": "#2C684C", "success-bg": "#E7F1EA",
        "warning": "#805916", "warning-bg": "#F6EDDA",
        "danger": "#AB3D33", "danger-bg": "#F9EBE6",
        "info": "#365F87", "info-bg": "#E8EEF5",
        "plot-1": "#59611F", "plot-2": "#365F87", "plot-3": "#8A4770", "plot-4": "#8B5A2B",
    },
    "dark": {
        "canvas": "#181A18", "surface": "#20231F", "subtle": "#292D26", "raised": "#30352C",
        "text": "#F1F2EA", "secondary": "#CBD0C1", "muted": "#A3AB98",
        "line": "#3D4437", "control": "#79846D",
        "accent": "#DCDE8D", "accent-hover": "#ECEEAD", "on-accent": "#181A18",
        "accent-ink": "#DCDE8D", "selected": "#343923", "focus": "#DCDE8D",
        "primary": "#DCDE8D", "primary-hover": "#ECEEAD", "on-primary": "#181A18",
        "success": "#9AD5AF", "success-bg": "#253C2E",
        "warning": "#E7C785", "warning-bg": "#3F3420",
        "danger": "#F0A49A", "danger-bg": "#462925",
        "info": "#A3C6E8", "info-bg": "#253747",
        "plot-1": "#DCDE8D", "plot-2": "#A3C6E8", "plot-3": "#D7A7CA", "plot-4": "#E2B98E",
    },
}
dimensions = {
    **{"space-" + str(n): str(n) + "px" for n in (4, 8, 12, 16, 24, 32, 48, 64, 96)},
    "radius-sm": "4px", "radius-md": "8px", "radius-lg": "12px",
    "control-sm": "32px", "control-md": "40px", "control-lg": "48px", "touch": "44px",
    "font-caption": "12px", "font-body": "14px", "font-reading": "16px",
    "font-subtitle": "20px", "font-title": "28px", "font-section": "40px", "font-display": "80px",
    "sidebar": "224px", "inspector": "288px", "topbar": "56px", "content-max": "1280px",
}
motion = {"fast": "120ms", "normal": "180ms", "enter": "320ms", "ease": "cubic-bezier(.22,1,.36,1)"}
fonts = {
    "sans": '"Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC", "Microsoft YaHei", sans-serif',
    "mono": 'ui-monospace, "SFMono-Regular", Consolas, "Liberation Mono", monospace',
}
tokens = {"version": "1.0.0", "product": "BioMaster 2.0", "format": "BioMaster grouped tokens; not a DTCG interchange file", "themes": themes, "dimensions": dimensions, "motion": motion, "fonts": fonts}
ROOT.joinpath("tokens.json").write_text(json.dumps(tokens, ensure_ascii=False, indent=2) + "\n")
css = ['/* Generated by build.py. Import before components.css. */', '@font-face { font-family: "Inter"; src: url("./assets/Inter.ttf") format("truetype"); font-weight: 100 900; font-style: normal; font-display: swap; }']
css.append(":root {\n" + "\n".join("  --bm-" + k + ": " + v + ";" for k, v in dimensions.items()) + "\n" + "\n".join("  --bm-motion-" + k + ": " + v + ";" for k, v in motion.items()) + "\n" + "\n".join("  --bm-font-" + k + ": " + v + ";" for k, v in fonts.items()) + "\n}")
for name, palette in themes.items():
    css.append((':root, [data-theme="light"]' if name == "light" else '[data-theme="dark"]') + " {\n  color-scheme: " + name + ";\n" + "\n".join("  --bm-" + k + ": " + v + ";" for k, v in palette.items()) + "\n}")
css.append('@media (prefers-reduced-motion: reduce) { :root { --bm-motion-fast: 0ms; --bm-motion-normal: 0ms; --bm-motion-enter: 0ms; } }')
ROOT.joinpath("tokens.css").write_text("\n\n".join(css) + "\n")
ROOT.joinpath("tokens-data.js").write_text("window.BIOMASTER_TOKENS = " + json.dumps(tokens, ensure_ascii=False) + ";\n")

def luminance(hex_value):
    values = [int(hex_value[i:i+2], 16) / 255 for i in (1, 3, 5)]
    linear = [x / 12.92 if x <= .04045 else ((x + .055) / 1.055) ** 2.4 for x in values]
    return sum(v * w for v, w in zip(linear, (.2126, .7152, .0722)))

def contrast(a, b):
    values = sorted((luminance(a), luminance(b)))
    return (values[1] + .05) / (values[0] + .05)

pairs = [(fg, bg, 4.5) for fg in ("text", "secondary", "muted") for bg in ("canvas", "surface", "subtle", "raised")]
pairs += [("on-accent", "accent", 4.5), ("on-accent", "accent-hover", 4.5), ("on-primary", "primary", 4.5), ("on-primary", "primary-hover", 4.5), ("accent-ink", "selected", 4.5)]
pairs += [(state, state + "-bg", 4.5) for state in ("success", "warning", "danger", "info")]
pairs += [(fg, bg, 3) for fg in ("focus", "control") for bg in ("canvas", "surface", "subtle")]
pairs += [("plot-" + str(n), "surface", 3) for n in range(1, 5)]
report = []
for theme, palette in themes.items():
    for fg, bg, minimum in pairs:
        value = contrast(palette[fg], palette[bg])
        assert value >= minimum, (theme, fg, bg, value, minimum)
        report.append({"theme": theme, "foreground": fg, "background": bg, "ratio": round(value, 3), "minimum": minimum, "pass": True})
ROOT.joinpath("contrast-report.json").write_text(json.dumps(report, indent=2) + "\n")
ROOT.joinpath("TOKEN-REFERENCE.md").write_text("# BioMaster token reference\n\nGenerated from `build.py`. Semantic names map directly to CSS custom properties.\n\n| CSS token | Light | Dark |\n| --- | --- | --- |\n" + "\n".join(f"| `--bm-{key}` | `{themes['light'][key]}` | `{themes['dark'][key]}` |" for key in themes['light']) + "\n\n## Dimensions\n\n" + "\n".join(f"- `--bm-{key}`: `{value}`" for key, value in dimensions.items()) + "\n")

# Editable campaign compositions; the original PNG is embedded without alteration.
logo = "data:image/png;base64," + base64.b64encode(ROOT.joinpath("assets/loop-b-light.png").read_bytes()).decode()
app = "data:image/png;base64," + base64.b64encode(ROOT.joinpath("assets/loop-b-app.png").read_bytes()).decode()

def campaign(file, width, height, square=False, dark=False):
    bg = "#181A18" if dark else "#F7F7F2"
    ink = "#F7F7F2" if dark else "#181A18"
    mute = "#CBD0C1" if dark else "#51564B"
    left = 72 if square else 80
    word_size = 112 if square else 120
    word_y = 210 if square else 200
    image_size = 360 if square else 380
    image_x = 630 if square else width - 500
    image_y = 570 if square else 135
    source = app if dark else logo
    subtitle_y = 305 if square else 300
    content = f'''<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}" role="img" aria-label="BioMaster 2.0 campaign template">
<title>BioMaster 2.0 — Research moves in loops</title>
<rect width="{width}" height="{height}" fill="{bg}"/>
<g font-family="Inter, Arial, sans-serif" fill="{ink}">
<text x="{left}" y="70" font-size="16" letter-spacing="2" fill="{mute}">BIOMASTER 2.0 / LOOP ENGINEERING</text>
<text x="{left-4}" y="{word_y}" font-size="{word_size}" letter-spacing="-7" font-weight="600">BioMaster<tspan fill="#929844">.</tspan></text>
<text x="{left}" y="{subtitle_y}" font-size="48" letter-spacing="-2">Research moves</text>
<text x="{left}" y="{subtitle_y+62}" font-size="48" letter-spacing="-2">in loops.</text>
<text x="{left}" y="{subtitle_y+133}" font-size="21" fill="{mute}">A workbench for computational research.</text>
<text x="{left}" y="{subtitle_y+167}" font-size="21" fill="{mute}">Chat. Notebook. Team.</text>
</g>
<image x="{image_x}" y="{image_y}" width="{image_size}" height="{image_size}" href="{source}"/>
<path d="M {left} {height-82} H {width-left}" stroke="{'#3D4437' if dark else '#D8DBD1'}"/>
<g font-family="Arial, sans-serif" font-size="14" letter-spacing="1" fill="{mute}">
<text x="{left}" y="{height-42}">THINK → EXECUTE → OBSERVE → REFINE ↲</text>
<text x="{width-left}" y="{height-42}" text-anchor="end">AI CODING FOR COMPUTATIONAL EXPERIMENTS</text>
</g></svg>'''
    ROOT.joinpath("templates", file).write_text(content)

campaign("social-1200x630.svg", 1200, 630)
campaign("slide-1600x900.svg", 1600, 900, dark=True)
campaign("square-1080x1080.svg", 1080, 1080, square=True)
print(f"Generated tokens, {len(report)} passing contrast checks, and 3 editable campaign templates.")
